### ISSUE TITLE
Certain emojis crash DB

### ISSUE THREAD

**Issue by LoLei** [r-lmr/lmrdashboard#53]
Sending "🐧" in a message in the channel crashes the backend, making the bot disconnect (and reconnect), neither displaying nor saving the message in the database.

Stacktrace:
```
(node:83735) UnhandledPromiseRejectionWarning: Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x90\xA7' for column `lmrdashboard`.`last_messages`.`message` at row 1
    at Query.Sequence._packetToError (/home/me/git/lmrdashboard/backend/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/me/git/lmrdashboard/backend/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/me/git/lmrdashboard/backend/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/me/git/lmrdashboard/backend/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/me/git/lmrdashboard/backend/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/me/git/lmrdashboard/backend/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/me/git/lmrdashboard/backend/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/me/git/lmrdashboard/backend/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    --------------------
    at Protocol._enqueue (/home/me/git/lmrdashboard/backend/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/me/git/lmrdashboard/backend/node_modules/mysql/lib/Connection.js:198:25)
    at /home/me/git/lmrdashboard/backend/node_modules/knex/lib/dialects/mysql/index.js:134:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/home/me/git/lmrdashboard/backend/node_modules/knex/lib/dialects/mysql/index.js:128:12)
    at Client_MySQL.query (/home/me/git/lmrdashboard/backend/node_modules/knex/lib/client.js:168:17)
    at Runner.query (/home/me/git/lmrdashboard/backend/node_modules/knex/lib/runner.js:151:36)
    at /home/me/git/lmrdashboard/backend/node_modules/knex/lib/runner.js:40:23
    at /home/me/git/lmrdashboard/backend/node_modules/knex/lib/runner.js:277:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:83735) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:83735) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aboft** [comment]
@maxaudron @LoLei 

/etc/my.cnf needs to be the following configuration and the bug should go away.

```
aboft:backend/ (fix-wait-for-auth) $ cat /etc/my.cnf                                                                                             [16:49:59]
[mysql]
default-character-set=utf8mb4

[mysqld]
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
init_connect='SET NAMES utf8mb4'
sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```

```
MariaDB [lmrdashboard]> select * from last_messages order by dateCreated desc limit 4;
+-------+-------------+---------+---------------------+
| user  | server      | message | dateCreated         |
+-------+-------------+---------+---------------------+
| aboft | #aboftytest | 🐧       | 2020-11-28 16:49:12 |
| aboft | #aboftytest | 🐧       | 2020-11-28 16:49:10 |
| aboft | #aboftytest | 🐧       | 2020-11-28 16:48:44 |
+-------+-------------+---------+---------------------+
3 rows in set (0.000 sec)
```
